uploads = []
outputs = []

[[generated]]
id = "5b_iy7-UEP1Sm38hFF_hk"
uri = "file://artifacts/casa-em-dia/public/hero-bg.png"
type = "image"
title = "warm home interior with tools"

[[generated]]
id = "ZEqES2ozr2HPDIWxqQxp6"
uri = "file://artifacts/casa-em-dia/public/profissional-manutencao.png"
type = "image"
title = "generated_image"
